# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_blog:
    resource: "@BlogBundle/Controller/BlogController.php"
    type:     annotation
    prefix:   /

_admin:
    resource: "@BlogBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin/dashboard

_post:
    resource: "@BlogBundle/Controller/PostController.php"
    type:     annotation
    prefix:   /admin/post    