# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_blog:
    resource: "@BlogBundle/Controller/BlogController.php"
    type:     annotation
    prefix:   /

_admin:
    resource: "@BlogBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

_posts:
    resource: "@BlogBundle/Controller/PostsController.php"
    type:     annotation
    prefix:   /admin/posts    

_comments:
    resource: "@BlogBundle/Controller/CommentsController.php"
    type:     annotation
    prefix:   /admin/comments    

_users:
    resource: "@BlogBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /admin/users    


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile